# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'document_category_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UIDocumentCategory(object):
    def setupUi(self, UIDocumentCategory):
        UIDocumentCategory.setObjectName("UIDocumentCategory")
        UIDocumentCategory.resize(429, 185)
        self.centralwidget = QtWidgets.QWidget(UIDocumentCategory)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.short_name_label = QtWidgets.QLabel(self.centralwidget)
        self.short_name_label.setObjectName("short_name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.short_name_label)
        self.short_name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.short_name_line_edit.setObjectName("short_name_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.short_name_line_edit)
        self.path_label = QtWidgets.QLabel(self.centralwidget)
        self.path_label.setObjectName("path_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.path_label)
        self.path_frame = QtWidgets.QHBoxLayout()
        self.path_frame.setObjectName("path_frame")
        self.path_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.path_line_edit.setObjectName("path_line_edit")
        self.path_frame.addWidget(self.path_line_edit)
        self.set_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_path_button.setObjectName("set_path_button")
        self.path_frame.addWidget(self.set_path_button)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.path_frame)
        self.validity_label = QtWidgets.QLabel(self.centralwidget)
        self.validity_label.setObjectName("validity_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.validity_label)
        self.validity_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.validity_line_edit.setObjectName("validity_line_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.validity_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttons_frame = QtWidgets.QHBoxLayout()
        self.buttons_frame.setObjectName("buttons_frame")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setObjectName("remove_button")
        self.buttons_frame.addWidget(self.remove_button)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setObjectName("apply_button")
        self.buttons_frame.addWidget(self.apply_button)
        self.verticalLayout.addLayout(self.buttons_frame)
        UIDocumentCategory.setCentralWidget(self.centralwidget)

        self.retranslateUi(UIDocumentCategory)
        QtCore.QMetaObject.connectSlotsByName(UIDocumentCategory)

    def retranslateUi(self, UIDocumentCategory):
        _translate = QtCore.QCoreApplication.translate
        UIDocumentCategory.setWindowTitle(_translate("UIDocumentCategory", "Document"))
        self.name_label.setText(_translate("UIDocumentCategory", "Наименование"))
        self.short_name_label.setText(_translate("UIDocumentCategory", "Краткое имя"))
        self.path_label.setText(_translate("UIDocumentCategory", "Папка"))
        self.set_path_button.setText(_translate("UIDocumentCategory", "Назначить"))
        self.validity_label.setText(_translate("UIDocumentCategory", "Срок действия"))
        self.remove_button.setText(_translate("UIDocumentCategory", "Удалить"))
        self.apply_button.setText(_translate("UIDocumentCategory", "Потвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIDocumentCategory = QtWidgets.QMainWindow()
    ui = Ui_UIDocumentCategory()
    ui.setupUi(UIDocumentCategory)
    UIDocumentCategory.show()
    sys.exit(app.exec_())
