# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information_field.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiInformationFieldWindow(object):
    def setupUi(self, UiInformationFieldWindow):
        UiInformationFieldWindow.setObjectName("UiInformationFieldWindow")
        UiInformationFieldWindow.resize(386, 201)
        self.centralwidget = QtWidgets.QWidget(UiInformationFieldWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.belonging_label = QtWidgets.QLabel(self.centralwidget)
        self.belonging_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.belonging_label.setObjectName("belonging_label")
        self.verticalLayout.addWidget(self.belonging_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.value_label = QtWidgets.QLabel(self.centralwidget)
        self.value_label.setObjectName("value_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.value_label)
        self.format_label = QtWidgets.QLabel(self.centralwidget)
        self.format_label.setObjectName("format_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.format_label)
        self.name_field = QtWidgets.QLineEdit(self.centralwidget)
        self.name_field.setObjectName("name_field")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_field)
        self.value_field = QtWidgets.QLineEdit(self.centralwidget)
        self.value_field.setObjectName("value_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_field)
        self.format_layout = QtWidgets.QHBoxLayout()
        self.format_layout.setObjectName("format_layout")
        self.set_text_format = QtWidgets.QRadioButton(self.centralwidget)
        self.set_text_format.setObjectName("set_text_format")
        self.format_layout.addWidget(self.set_text_format)
        self.set_date_format = QtWidgets.QRadioButton(self.centralwidget)
        self.set_date_format.setObjectName("set_data_format")
        self.format_layout.addWidget(self.set_date_format)
        self.set_combo_format = QtWidgets.QRadioButton(self.centralwidget)
        self.set_combo_format.setObjectName("set_combo_format")
        self.format_layout.addWidget(self.set_combo_format)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.format_layout)
        self.verticalLayout.addLayout(self.formLayout)
        self.all_buttons = QtWidgets.QVBoxLayout()
        self.all_buttons.setObjectName("all_buttons")

        self.down_buttons = QtWidgets.QHBoxLayout()
        self.down_buttons.setObjectName("down_buttons")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setObjectName("clear_button")
        self.down_buttons.addWidget(self.clear_button)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setObjectName("apply_button")
        self.down_buttons.addWidget(self.apply_button)
        self.all_buttons.addLayout(self.down_buttons)
        self.verticalLayout.addLayout(self.all_buttons)
        UiInformationFieldWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UiInformationFieldWindow)
        QtCore.QMetaObject.connectSlotsByName(UiInformationFieldWindow)

    def retranslateUi(self, UiInformationFieldWindow):
        _translate = QtCore.QCoreApplication.translate
        UiInformationFieldWindow.setWindowTitle(_translate("UiInformationFieldWindow", "Информационое поле"))
        self.belonging_label.setText(_translate("UiInformationFieldWindow", "Пример: Водитель - Максимв И."))
        self.name_label.setText(_translate("UiInformationFieldWindow", "Наименование"))
        self.value_label.setText(_translate("UiInformationFieldWindow", "Значение"))
        self.format_label.setText(_translate("UiInformationFieldWindow", "Формат"))
        self.set_text_format.setText(_translate("UiInformationFieldWindow", "Текст"))
        self.set_date_format.setText(_translate("UiInformationFieldWindow", "Дата"))
        self.set_combo_format.setText(_translate("UiInformationFieldWindow", "Комбинированый"))
        self.clear_button.setText(_translate("UiInformationFieldWindow", "Отмена"))
        self.apply_button.setText(_translate("UiInformationFieldWindow", "Потвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiInformationFieldWindow = QtWidgets.QMainWindow()
    ui = UiInformationFieldWindow()
    ui.setupUi(UiInformationFieldWindow)
    UiInformationFieldWindow.show()
    sys.exit(app.exec_())
