# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information_fields.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiInformationFields(object):
    def setupUi(self, UiInformationFields):
        UiInformationFields.setObjectName("UiInformationFields")
        UiInformationFields.resize(398, 449)
        self.centralwidget = QtWidgets.QWidget(UiInformationFields)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName("scroll")
        self.information_fields_area = QtWidgets.QWidget()
        self.information_fields_area.setGeometry(QtCore.QRect(0, 0, 374, 320))
        self.information_fields_area.setObjectName("information_fields_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.information_fields_area)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.information_fields_form = QtWidgets.QFormLayout()
        self.information_fields_form.setObjectName("information_fields_form")
        self.verticalLayout_2.addLayout(self.information_fields_form)
        self.scroll.setWidget(self.information_fields_area)
        self.verticalLayout.addWidget(self.scroll)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout.addWidget(self.remove_button)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        UiInformationFields.setCentralWidget(self.centralwidget)

        self.retranslateUi(UiInformationFields)
        QtCore.QMetaObject.connectSlotsByName(UiInformationFields)

    def retranslateUi(self, UiInformationFields):
        _translate = QtCore.QCoreApplication.translate
        UiInformationFields.setWindowTitle(_translate("UiInformationFields", "Категория"))
        self.add_button.setText(_translate("UiInformationFields", "Добавить"))
        self.remove_button.setText(_translate("UiInformationFields", "Удалить"))
        self.save_button.setText(_translate("UiInformationFields", "Сохронить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiInformationFields = QtWidgets.QMainWindow()
    ui = Ui_UiInformationFields()
    ui.setupUi(UiInformationFields)
    UiInformationFields.show()
    sys.exit(app.exec_())
