# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_table_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiSettingsTableWindow(object):
    def setupUi(self, UiSettingsTableWindow):
        UiSettingsTableWindow.setObjectName("UiSettingsTableWindow")
        UiSettingsTableWindow.resize(371, 556)
        self.centralwidget = QtWidgets.QWidget(UiSettingsTableWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.group_samples = QtWidgets.QGroupBox(self.centralwidget)
        self.group_samples.setObjectName("group_samples")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_samples)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scroll_samples = QtWidgets.QScrollArea(self.group_samples)
        self.scroll_samples.setWidgetResizable(True)
        self.scroll_samples.setObjectName("scroll_samples")
        self.samples_area = QtWidgets.QWidget()
        self.samples_area.setGeometry(QtCore.QRect(0, 0, 335, 199))
        self.samples_area.setObjectName("samples_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.samples_area)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.samples_layout = QtWidgets.QVBoxLayout()
        self.samples_layout.setObjectName("samples_layout")
        self.verticalLayout_2.addLayout(self.samples_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scroll_samples.setWidget(self.samples_area)
        self.verticalLayout_6.addWidget(self.scroll_samples)
        self.buttons_area = QtWidgets.QHBoxLayout()
        self.buttons_area.setObjectName("buttons_area")
        self.save_sample_buttons = QtWidgets.QPushButton(self.group_samples)
        self.save_sample_buttons.setObjectName("save_sample_buttons")
        self.buttons_area.addWidget(self.save_sample_buttons)
        self.set_order_sample_buttons = QtWidgets.QPushButton(self.group_samples)
        self.set_order_sample_buttons.setObjectName("set_order_sample_buttons")
        self.buttons_area.addWidget(self.set_order_sample_buttons)
        self.remove_sample_buttons = QtWidgets.QPushButton(self.group_samples)
        self.remove_sample_buttons.setObjectName("remove_sample_buttons")
        self.buttons_area.addWidget(self.remove_sample_buttons)
        self.verticalLayout_6.addLayout(self.buttons_area)
        self.verticalLayout_4.addWidget(self.group_samples)
        self.group_columns = QtWidgets.QGroupBox(self.centralwidget)
        self.group_columns.setObjectName("group_columns")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.group_columns)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scroll_columns = QtWidgets.QScrollArea(self.group_columns)
        self.scroll_columns.setWidgetResizable(True)
        self.scroll_columns.setObjectName("scroll_columns")
        self.columns_area = QtWidgets.QWidget()
        self.columns_area.setGeometry(QtCore.QRect(0, 0, 335, 200))
        self.columns_area.setObjectName("columns_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.columns_area)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.columns_layout = QtWidgets.QVBoxLayout()
        self.columns_layout.setObjectName("columns_layout")
        self.verticalLayout.addLayout(self.columns_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scroll_columns.setWidget(self.columns_area)
        self.verticalLayout_5.addWidget(self.scroll_columns)
        self.change_columns = QtWidgets.QPushButton(self.group_columns)
        self.change_columns.setObjectName("change_columns")
        self.verticalLayout_5.addWidget(self.change_columns)
        self.verticalLayout_4.addWidget(self.group_columns)
        UiSettingsTableWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UiSettingsTableWindow)
        QtCore.QMetaObject.connectSlotsByName(UiSettingsTableWindow)

    def retranslateUi(self, UiSettingsTableWindow):
        _translate = QtCore.QCoreApplication.translate
        UiSettingsTableWindow.setWindowTitle(_translate("UiSettingsTableWindow", "Настройки таблицы"))
        self.group_samples.setTitle(_translate("UiSettingsTableWindow", "Шаблоны таблицы"))
        self.save_sample_buttons.setText(_translate("UiSettingsTableWindow", "Сохранить"))
        self.set_order_sample_buttons.setText(_translate("UiSettingsTableWindow", "Изменить"))
        self.remove_sample_buttons.setText(_translate("UiSettingsTableWindow", "Удалить"))
        self.group_columns.setTitle(_translate("UiSettingsTableWindow", "Столбцы"))
        self.change_columns.setText(_translate("UiSettingsTableWindow", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiSettingsTableWindow = QtWidgets.QMainWindow()
    ui = Ui_UiSettingsTableWindow()
    ui.setupUi(UiSettingsTableWindow)
    UiSettingsTableWindow.show()
    sys.exit(app.exec_())
